### ISSUE TITLE
app-tasks - roadmap to finish

### ISSUE THREAD

**Issue by Gutschlhofer** [fineprint-global/io-visualization#10]
- [x] percent behind nodes (_bugged!_)
- [x] loading indicator when calculating (like in SCP-HAT)
- [x] allow user to change the aggregate for the top_n countries
- [x] aggregate flows
- [x] on top/bottom of graph: labels for each "node-column" to explain what is happening in each step (.., (final) producing region, final product, consuming region)
- [x] remove the color the year slider makes when selecting anything but the first year, makes it seem like it's a year range (`span.irs-bar-edge` and `span.irs-bar` remove border and background)
- [x] if there is already a food node (e.g. Bovine Meat) the rest-Food node should not be called "Food" but "Other food", same for nonfood

open questions rather than to-dos:
- alternating colors for flows? (unlikely possible)
- check if we can write node name into node

**Comment by Gutschlhofer** [comment]
~Bug: The percent are only calculated once, not for each node separately (i.e. producing region BRA should not be the exact same percentage as consuming region BRA)!~
